- name: install and start  the nginx
  hosts: nginx
  become: yes
  tasks:
  - name: instll nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start nginx
    ansible.builtin.service:
      name:  nginx
      state: started
      enabled: yes